### ISSUE TITLE
Build cmake packages with RelWithDebInfo

### ISSUE THREAD

**Issue by knazarov** [bigbes/taranrocks#1]
Currently the cmake packages are built with CMAKE_BUILD_TYPE=Release.
It will make it hard to debug code in production.

**Comment by bigbes** [comment]
https://github.com/keplerproject/luarocks/blob/d524b515c67ceded00a15c2617283f81a2f21f7c/src/luarocks/build/cmake.lua
It seems like it can't be build without Release
